export default [{
  value:'realEstate.name',
  label:'地产商',
  required:true,
},{
  value:'name',
  label:'小区名称',
  required:true,
},{
  value:'setPoint.name',
  label:'归集点',
  required:true,
},{
  value:'propertyManagment.name',
  label:'物业公司',
  required:true,
},{
  value:'number',
  label:'编号'
},{
  value:'area',
  label:'地址'
},{
  value:'buildingCount',
  label:'楼宇数'
},{
  value:'officeRoom',
  label:'物管办公用房'
},{
  value:'officeRoomSquare',
  label:'物管办公用房面积',
  needSum:true
},{
  value:'businessRoom',
  label:'物管经营用房'
},{
  value:'businessRoomSquare',
  label:'物管经营用房面积',
  needSum:true
},{
  value:'publicRoom',
  label:'公建用房'
},{
  value:'publicRoomSquare',
  label:'公建用房面积',
  needSum:true
}]